/* Generated By:JavaCC: Do not edit this line. CSPParserConstants.java */
package org.finra.datagenerator.csp.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LITERAL = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"@END\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"->\"",
    "\"T\"",
    "\"==\"",
    "\"~=\"",
    "<LITERAL>",
  };

}
